from textes import *

text_steps = [
    [ADD_WORD_TEXT, ADD_WORD_READ, ADD_WORD_END],
    [ADD_STOP_WORD_TEXT, ADD_STOP_WORD_READ, ADD_STOP_WORD_END],
    [DEL_WORD_TEXT, DEL_WORD_READ, DEL_WORD_END],
    [DEL_STOP_WORD_TEXT, DEL_STOP_WORD_READ, DEL_STOP_WORD_END]
]
